### ISSUE TITLE
System.EntryPointNotFoundException: 'Unable to find an entry point named 'new_aubio_source' in DLL 'aubio'.'

### ISSUE THREAD

**Issue by MiLO83** [aybe/aubio.net#5]
When using Aubio in a new project, I get this error...

System.EntryPointNotFoundException: 'Unable to find an entry point named 'new_aubio_source' in DLL 'aubio'.'

I am a Unity3D programmer and not very familiar with Visual Studio, so the error may be on my part.
I am hoping for a solution ASAP as my app compiles but runs with this error. 
This does not involve Unity3D tho, I am not using Unity3D for this project currently.

Thanks :)

**Comment by aybe** [comment]
It's been months I haven't worked on this ........ however,

I tried the followed right now and it just worked:
 - build the develop branch
 - copied the dependencies at https://github.com/aybe/aubio.net/releases to solution folder
    (this is because all the samples references Aubio.NET.Test.Helper which copy these to /bin/debug)
 - run Aubio.NET.TestFilters
 - works !

So I don't see any error on my side, try that.

What I remember from my last work
 - I used to have an AnyCPU loader that would either load DLLs from /x86 or /x64 subdir according current environment, but I removed it, i.e. it's just as usual where DLLs have to be next to your EXE and match bitness.
 - 'aubio' only as DLLImport is fine because it works for regular .NET but more importantly is required for Unity as you might know
 - the 'Aubio' project is deprecated, the one valid is 'Aubio.NET'
   (it should be removed from the repo but I haven't for some reason I can't remember now)
 - I believe my dependencies package uses my own fork https://github.com/aybe/aubio/commits/develop because the author never merged them, one way to check would be the imports of my fixes/additions

(I wrote that wrapper for fun but actually don't use it all ... I don't have the time anymore for music stuff)

However I tested it extensively before publishing, if for some reason you have weird results:
- beware of outdated aubio docs online, prefer the ones in sources
- if something does not work as expected, you'll need a debug environment, i.e. fork vcpkg. build aubio, then debug my wrapper with produced binaries (another complete story)

:)

**Comment by MiLO83** [comment]
Thank you! :)
I will see what I can come up with. :)
