### ISSUE TITLE
Invert ThrowIfNot, correct passing of set_minioi

### ISSUE THREAD

**Issue by Laubeee** [aybe/aubio.net#6]
Hi, thanks for this port of the aubio library API!
I think I have 2 errors to report:
1. I encounter errors when I try to set any kind of parameters in this line:
https://github.com/aybe/aubio.net/blob/master/Aubio/AubioObject.cs#L37
It seems to me this is a mistake as you expect aubio to return `true` on success, but the functions (as normal in C) return 0 (error code) if everything went fine. Therefore an exception is always raised.

2. While investigating this I also saw you pass the number of samples on [Onset.MinimumInterOnsetInterval](https://github.com/aybe/aubio.net/blob/master/Aubio/Detection/Onset.cs#L106) but according to the API it wants the milliseconds.

On a side note, could you explain what the Aubio.NET project is about? it seems to me everything is already in the Aubio project?
Also: where did you find libaubio-6.dll ? I found only libaubio-5 (for windows). Did you build it yourself? Which version auf aubio was that?

**Comment by aybe** [comment]
The latest branch is develop:

https://github.com/aybe/aubio.net/tree/develop

Check its README file for the whole story, that should answer your questions.

And for no. 2 there's a strong possibility this is a bug 😃.

**Comment by Laubeee** [comment]
OK, I see. So, do you recommend using develop-branch in a productive environment? Is it stable / well tested? (If yes, why dont you merge it to master?)

**Comment by Laubeee** [comment]
ah, about 2.  I have to correct: this is not a bug. I see now there are multiple API calls and you can set it in samples, seconds or milliseconds.

**Comment by aybe** [comment]
Yes, the new folder is the better version I've written but did not remove the old one for some reason I don't remember.

That's pretty old now so I've forgotten about it, one thing though, I recommend that you read the docs of the original aubio directly from the last sources because the ones on the site haven't been updated in a while I guess.

😊

Le 16 avr. 2019 09:59, Laubeee <notifications@github.com> a écrit :

ah, about 2. I have to correct: this is not a bug. I see now there are multiple API calls and you can set it in samples, seconds or milliseconds.
